-- Create Watchlist Table
CREATE TABLE IF NOT EXISTS user_watchlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  symbol TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, symbol)
);

-- Note: Ensure 'users' table exists and 'id' matches (usually BIGINT or UUID depending on existing schema)
-- Based on login.js, users.id seems to be used. Let's verify users table schema if needed, 
-- but IF NOT EXISTS is safe.
